development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: giving_connection_production
  <% if ENV.fetch("REDIS_URL", "").start_with?("rediss://") %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  <% end %>

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: giving_connection_staging
  <% if ENV.fetch("REDIS_URL", "").start_with?("rediss://") %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  <% end %>
